import {
  RTK,
  ReduxToolkit,
} from '../../deps.ts'

const {
  createApi,
  fetchBaseQuery,
} = ReduxToolkit

export const apiSlice = createApi({
  reducerPath: 'api', // the top-level field under state that this will populate
  baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
  endpoints: (builder) => ({
    getLanes: builder.query({
      query: () => '/lanes',
    }),
  }),
})

// the names here are autogenerated
export const { useGetLanesQuery } = apiSlice
